name: learn-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo Hello world
        name: echo command
      - run: find .
        name: list of files
      - run: echo  ok
        name: code build
      - run: echo ok
        name: code test
      - run: echo /opt/sonar-scanner-6.0.0.4432-linux/bin/sonar-scanner -Dsonar.host.url=http://34.228.192.233:9000  -Dsonar.projectkey=${{inputs.project-name}} -Dsonar.qualitygate.wait=true
        name: code review
      - run: echo ok
        name: fs release software
