name: learn-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  reuse:
    runs-on: [self-hosted]

    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo Hello world
        name: echo command
      - name: Import Vault Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://34.238.172.0:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            common/data/sonar_credentials/username | username ;
            common/data/sonar_credentials/password | passwords ;

      - run: find .
        name: list of files
      - run: echo  ok
        name: code build
      - run: echo ok
        name: code test
      - run: echo hello sonar scanner cli
        name: code review
      - run: echo ok
        name: fs release software
