name: learn-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo Hello world
        name: display mssg
      - run: ls -Alr
        name: list of files
      - run: echo "project-name" ${{inputs.project-name}}
        name: project name

