name: learn-github-actions
on:
  workflow_call:
      inputs:
        project-name:
          required: true
          type: string
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: code build
        name: echo build
      - run: code test
        name: echo test
      - run: echo /opt/sonarscannercli/bin/sonar-scanner -Dsonar.host.url=http://34.228.192.233:9000 -Dsonar.login=admin -Dsonar.password=admin123 -Dsonar.projectkey={{inputs.project-name}} -Dsonar.qualitygate.wait=true
        name: echo code review
      - run: release software
        name: echo release software
