name: learn-github-actions
on: [workflow_call]

jobs:
  reuse:
    runs-on: [self-hosted]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: find .
        name: list of files
      - run: echo  ok
        name: code build
      - run: echo ok
        name: code test
      - run: echo hello sonar scanner cli
        name: code review
      - run: echo ok
        name: release software
