name: learn-github-actions
on: [workflow_call]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: echo Hello world
        name: Run echo command
      - run: find .
        name: list of files
