name: learn-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      vault_token:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://3.81.127.67:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            common/data/sonar_credentials/username | username ;
            common/data/sonar_credentials/password | password ;
      - run: echo Hello world
        name: display mssg
      - run: ls -Alr
        name: list of files
      - run: echo  ${{inputs.project-name}}
        name: project name
      - run: echo ${{secrets.vault_token}}
        name: get token
      - run: echo /opt/sonarscannercli/bin/sonar-scanner  -Dsonar.login="${{ steps.import-secrets.outputs.username }} -Dsonar.password=${{ steps.import-secrets.outputs.password }} -Dsonar.projectkey={{inputs.project-name}}
        name: get sonar vault

