name: learn-github-actions
on: [workflow_call]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - run: find .
        name: list of files

      - run: echo  ok
        name: code build
      - run: echo ok
        name: code test

