name: reusable curl github actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      release_archive_file:
        required: true
        type: string
    secrets:
      VAULT_TOKEN:
        required: true

jobs:
  job_curl:
    runs-on: [ubuntu-latest]
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: get list of files
        run: ls -l
      - run: env
        name: display env
      - run: echo ${{inputs.project-name}}
        name: get project name
      - run: echo ${{secrets.VAULT_TOKEN}}
        name: get vault token
      - run: echo ${{inputs.release_archive_file}}
        name: artifact  file
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://52.90.98.233:8200
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            common/data/artifactory artifactory_user | artifactory_user;
            common/data/artifactory artifactory_password | artifactory_password ;
      - name: zip files
        uses: vimtor/action-zip@v1.2
        with:
          files: ${{inputs.release_artifact_file}}
          dest: artifact.zip ${{inputs.release_artifact_file}}
      - name: artifactory user
        run: echo ${{steps.import-secrets.outputs.artifactory_user}}
      - name: artifactory password
        run: echo ${{steps.import-secrets.outputs.artifactory_password}}s

      - name: upload artifact to jfrog
        run: $ curl -v --user ${{steps.import-secrets.outputs.artifactory_user}}:${{steps.import-secrets.outputs.artifactory_password}} --data-binary @artifact.zip -X PUT http://18.232.76.52:8081/artifactory/expense-backend/artifact.zip
