name: release-reuse-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      JF_USER:
        required: true
        type: string


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: ls -lh
        name: list of files
      - run: echo ${{inputs.project-name}}
        name: get project name
      - run: echo ${{secrets.JF_USER}}
        name: get username





