name: release-reuse-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      release_archive_file:
        required: true
        type: string
    secrets:
      JF_URL:
        required: true
      JF_USER:
        required: true
      JF_PASSWORD:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: ls -lh
        name: upload artifact file through jfrog cli
      - name: jfrog through cli
        uses: jfrog/setup-jfrog-cli@v4
      - run: ls -lh
        name: upload artifact file through jfrog cli
      - run: echo "${{ secrets.JF_URL }} ${{ secrets.JF_USER }} ${{ secrets.JF_PASSWORD }}"
        name: get jfrog credentials
      - name: Import Secret
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://54.160.185.91:8200
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
                  common/data/artifactory artifactory_user | artifactory_user ;
                  common/data/artifactory artifactory_password | artifactory_password ;
      - uses: vimtor/action-zip@v1.2
        with:
          files: ${{inputs.release_archive_file}}
          dest: ${{inputs.project-name}}.zip
      - run: echo ${{inputs.project-name}}.zip
        name: zip files
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
      - run: |
          jf rt ping
#          jf rt u ${{inputs.project-name}}.zip ${{inputs.project-name}}/${{inputs.project-name}}.zip



     



