name: release-reuse-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: ls -lh
        name: upload artifact file through jfrog cli
      - name: jfrog through cli
        uses: jfrog/setup-jfrog-cli@v4


     



