name: release-reuse-github-actions
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      JF_URL:
        required: true
      JF_USER:
        required: true
      JF_PASSWORD:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - run: ls -lh
        name: upload artifact file through jfrog cli
      - name: jfrog through cli
        uses: jfrog/setup-jfrog-cli@v4
      - run: ls -lh
        name: upload artifact file through jfrog cli
      - run: echo "${{ secrets.JF_URL }} ${{ secrets.JF_USER }} ${{ secrets.JF_PASSWORD }}"
        name: get jfrog credentials
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}



     



